services:
  cpp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp-server
    ports:
      - "8080:8080"
    restart: unless-stopped 
    networks:
      - cpp-network

  llama-cpp:
    image: ghcr.io/ggerganov/llama.cpp:full
    container_name: llama-cpp-server
    restart: unless-stopped
    ports:
      - "1234:1234"
    volumes:
      - ./models:/models
    command: [
      "--server",
      "--model", "/models/saiga_nemo_12b.Q4_K_S.gguf", # path to your model here
      "--ctx-size", "2048",
      "--host", "0.0.0.0",
      "--port", "1234"
    ]
    networks:
      - cpp-network

networks:
  cpp-network:
    driver: bridge